### ISSUE TITLE
Unknown Error after entering auth code

### ISSUE THREAD

**Issue by 0nitsoga** [nikshriv/hassio-addons#1]
I was able to get to the final step and received an "unknown error" after entering the auth code. 

Here are the full log details

```
2022-06-12 23:21:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:21:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:21:54 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:21:54 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:21:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:21:54 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_geocode which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:21:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration cync_lights which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-12 23:25:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/cync_lights/config_flow.py", line 208, in async_step_google_auth_code
self.data['data']['cync_room_data'] = await self.cync_hub.get_cync_config()
File "/config/custom_components/cync_lights/get_user_data.py", line 66, in get_cync_config
if bulb['switchID'] != 0:
KeyError: 'switchID'
```

**Comment by nikshriv** [comment]
I'm working on a revamp of this integration so that the cync lights addon is not required. All the IO will be coming from the integration itself, so I think once it's done, this issue should go away. Also, currently google has changed their Oauth policy and will not be allowing the authentication flow I used in this integration. Working on that too.

**Comment by louisostrowski** [comment]
> I'm working on a revamp of this integration so that the cync lights addon is not required. All the IO will be coming from the integration itself, so I think once it's done, this issue should go away. Also, currently google has changed their Oauth policy and will not be allowing the authentication flow I used in this integration. Working on that too.

Also patiently waiting :)

**Comment by nikshriv** [comment]
> I was able to get to the final step and received an "unknown error" after entering the auth code.
> 
> Here are the full log details
> 
> ```
> 2022-06-12 23:21:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:21:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:21:54 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:21:54 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:21:54 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:21:54 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_geocode which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:21:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration cync_lights which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2022-06-12 23:25:10 ERROR (MainThread) [aiohttp.server] Error handling request
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
> resp = await request_handler(request)
> File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
> resp = await handler(request)
> File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
> result = await result
> File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
> return await super().post(request, flow_id)
> File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
> result = await method(view, request, *args, **kwargs)
> File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
> result = await self._flow_mgr.async_configure(flow_id, data)
> File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
> result = await self._async_handle_step(
> File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
> result: FlowResult = await getattr(flow, method)(user_input)
> File "/config/custom_components/cync_lights/config_flow.py", line 208, in async_step_google_auth_code
> self.data['data']['cync_room_data'] = await self.cync_hub.get_cync_config()
> File "/config/custom_components/cync_lights/get_user_data.py", line 66, in get_cync_config
> if bulb['switchID'] != 0:
> KeyError: 'switchID'
> ```

I made a couple of changes and this should fix the bug you found. Let me know if it works.

**Comment by 0nitsoga** [comment]
Tried again, new error. Happy to work together on this live if you'd like. Find me on twitter. I have a development background and would love to assist.

```
Logger: custom_components.cync_lights.config_flow
Source: custom_components/cync_lights/config_flow.py:65
Integration: cync_lights
First occurred: 1:26:17 PM (3 occurrences)
Last logged: 1:26:29 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/cync_lights/config_flow.py", line 173, in async_step_client_secret
    self.auth_url = await get_google_auth_url(self.hass, self.google_hub, user_input, self.flow_id, redirect_uri)
  File "/config/custom_components/cync_lights/config_flow.py", line 65, in get_google_auth_url
    response = await hub.get_google_auth_url(hass, json.loads(user_input["client_secret"]), flow_id, redirect_uri)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nikshriv** [comment]
Did you copy and paste the entire content of your client secret json file? This error occurs if the pasted info is not valid json. Give it another try and let me know if that works.
